services:
  dev-db:
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER]" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DB_HOST=dev-db
#    depends_on:
#      dev-db:
#        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./src:/code/src
      - ./migrations:/code/migrations/
    command: >
      sh -c "while ! nc -z dev-db 5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      /code/.venv/bin/alembic upgrade head &&
      /code/.venv/bin/uvicorn src.main:fastfitapi --host 0.0.0.0 --port 8080"

volumes:
  db_data: