services:
  dev-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - DB_PORT=$DB_PORT
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "$DB_PORT:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    env_file:
      - .env
    build:
      context: .
    depends_on:
      - dev-db
    ports:
      - "8080:8080"
    command: ["/code/.venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]


volumes:
  db_data: