"""exercises done

Revision ID: 0fefd6c89856
Revises: 6c2fde7b6037
Create Date: 2025-07-24 18:23:37.742392

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fefd6c89856"
down_revision: Union[str, Sequence[str], None] = "6c2fde7b6037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("muscle_group", sa.String(length=255), nullable=False),
        sa.Column(
            "equipment_required", postgresql.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column(
            "difficulty",
            postgresql.ENUM(
                "BEGINNER", "INTERMEDIATE", "ADVANCED", name="difficulty_enum"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("exercise_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercises")
    # ### end Alembic commands ###
