"""one to one profile user

Revision ID: 180a2710313a
Revises: c371be70b8eb
Create Date: 2025-07-25 21:37:25.834686

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "180a2710313a"
down_revision: Union[str, Sequence[str], None] = "c371be70b8eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profile", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="unique")
    # ### end Alembic commands ###
