"""session_exercises_added

Revision ID: 1da2995a16c9
Revises: addcaf42a687
Create Date: 2025-07-24 18:38:44.615854

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da2995a16c9"
down_revision: Union[str, Sequence[str], None] = "addcaf42a687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_exercises",
        sa.Column("session_exercise_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("distance_km", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.exercise_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_exercise_id"),
    )
    op.create_index(
        "idx_session_exercises", "session_exercises", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_session_exercises", table_name="session_exercises")
    op.drop_table("session_exercises")
    # ### end Alembic commands ###
