"""plan_feedback_done

Revision ID: 4c019a21ab29
Revises: 1da2995a16c9
Create Date: 2025-07-24 18:41:18.619729

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c019a21ab29"
down_revision: Union[str, Sequence[str], None] = "1da2995a16c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_feedback",
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("completion_percentage", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("effectiveness_rating", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "completion_percentage BETWEEN 0 AND 100",
            name="check_completion_percentage",
        ),
        sa.CheckConstraint(
            "effectiveness_rating BETWEEN 1 AND 10", name="check_effectiveness_rating"
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["workout_plans.plan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        "idx_user_feedback", "plan_feedback", ["user_id", "plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_feedback", table_name="plan_feedback")
    op.drop_table("plan_feedback")
    # ### end Alembic commands ###
