"""profile default

Revision ID: 4fe7bf7bfd7b
Revises: ebcb6bc0e75e
Create Date: 2025-07-24 23:19:45.710518

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4fe7bf7bfd7b"
down_revision: Union[str, Sequence[str], None] = "ebcb6bc0e75e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
