"""added cascade delete

Revision ID: 512d1c99b5d5
Revises: d943dc90d950
Create Date: 2025-08-03 08:40:05.011541

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "512d1c99b5d5"
down_revision: Union[str, Sequence[str], None] = "d943dc90d950"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("workout_sessions_user_id_fkey"), "workout_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "workout_sessions", "users", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("workout_sessions_user_id_fkey"),
        "workout_sessions",
        "users",
        ["user_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###
