"""profile default

Revision ID: 7d3916d25174
Revises: b72b38ebca0f
Create Date: 2025-07-24 23:33:48.520319

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7d3916d25174"
down_revision: Union[str, Sequence[str], None] = "b72b38ebca0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
