"""profile default

Revision ID: 9ab021931889
Revises: 40d42d1ef483
Create Date: 2025-07-24 23:22:19.115976

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9ab021931889"
down_revision: Union[str, Sequence[str], None] = "40d42d1ef483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
