"""workout_session_done

Revision ID: addcaf42a687
Revises: 062494f6dbe2
Create Date: 2025-07-24 18:36:39.510320

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "addcaf42a687"
down_revision: Union[str, Sequence[str], None] = "062494f6dbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("perceived_intensity", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("session_type", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "perceived_intensity BETWEEN 1 AND 10",
            name="check_perceived_intensity_range",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("idx_user_sessions", "workout_sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_sessions", table_name="workout_sessions")
    op.drop_table("workout_sessions")
    # ### end Alembic commands ###
