"""nullable_fixes

Revision ID: b55daa179242
Revises: 4c019a21ab29
Create Date: 2025-07-24 18:51:22.976146

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b55daa179242"
down_revision: Union[str, Sequence[str], None] = "4c019a21ab29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercises",
        "difficulty",
        existing_type=postgresql.ENUM(
            "BEGINNER", "INTERMEDIATE", "ADVANCED", name="difficulty_enum"
        ),
        nullable=False,
    )
    op.alter_column(
        "plan_feedback",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "session_exercises", "sets", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "session_exercises", "reps", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "workout_plans",
        "generated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "workout_plans", "focus_area", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "workout_plans",
        "ai_model_version",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workout_plans",
        "ai_model_version",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "workout_plans", "focus_area", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "workout_plans",
        "generated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "session_exercises", "reps", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "session_exercises", "sets", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "plan_feedback",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "exercises",
        "difficulty",
        existing_type=postgresql.ENUM(
            "BEGINNER", "INTERMEDIATE", "ADVANCED", name="difficulty_enum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
