"""column lengths fixed

Revision ID: c0b082b17b8e
Revises: f42789a53e66
Create Date: 2025-07-25 01:50:46.939224

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c0b082b17b8e"
down_revision: Union[str, Sequence[str], None] = "f42789a53e66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercises",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises",
        "muscle_group",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises",
        "equipment_required",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
        type_=postgresql.ARRAY(sa.String(length=100)),
        existing_nullable=True,
    )
    op.alter_column(
        "workout_plans",
        "ai_model_version",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "workout_plans",
        "focus_area",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workout_plans",
        "ai_model_version",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises",
        "equipment_required",
        existing_type=postgresql.ARRAY(sa.String(length=100)),
        type_=postgresql.ARRAY(sa.VARCHAR(length=255)),
        existing_nullable=True,
    )
    op.alter_column(
        "exercises",
        "muscle_group",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "workout_plans",
        "focus_area",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )

    # ### end Alembic commands ###
