"""column lengths fixed

Revision ID: c371be70b8eb
Revises: c0b082b17b8e
Create Date: 2025-07-25 02:00:00.856651

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c371be70b8eb"
down_revision: Union[str, Sequence[str], None] = "c0b082b17b8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
