"""deletion cascade added to user profile

Revision ID: d943dc90d950
Revises: 8806796abc37
Create Date: 2025-07-31 09:45:56.531386

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d943dc90d950"
down_revision: Union[str, Sequence[str], None] = "8806796abc37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("profile_user_id_fkey"), "profile", type_="foreignkey")
    op.create_foreign_key(
        None, "profile", "users", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.create_foreign_key(
        op.f("profile_user_id_fkey"), "profile", "users", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###
