"""user_profile default value set

Revision ID: dd0c66a2b301
Revises: b55daa179242
Create Date: 2025-07-24 22:49:47.085079

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd0c66a2b301"
down_revision: Union[str, Sequence[str], None] = "b55daa179242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE gender_enum AS ENUM ('male', 'female', 'other', 'unspecified')"
    )
    op.execute(
        "CREATE TYPE fitness_enum AS ENUM ('beginner', 'intermediate', 'advanced')"
    )
    op.execute(
        "CREATE TYPE primary_goal_enum AS ENUM ('lose_weight', 'build_muscle', 'maintain_health', 'improve_endurance')"
    )

    op.execute(
        "ALTER TABLE profile ALTER COLUMN gender TYPE gender_enum USING gender::text::gender_enum"
    )
    op.execute(
        "ALTER TABLE profile ALTER COLUMN fitness_level TYPE fitness_enum USING fitness_level::text::fitness_enum"
    )
    op.execute(
        "ALTER TABLE profile ALTER COLUMN primary_goal TYPE primary_goal_enum USING primary_goal::text::primary_goal_enum"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE profile ALTER COLUMN primary_goal TYPE VARCHAR USING primary_goal::text"
    )
    op.execute(
        "ALTER TABLE profile ALTER COLUMN fitness_level TYPE VARCHAR USING fitness_level::text"
    )
    op.execute(
        "ALTER TABLE profile ALTER COLUMN gender TYPE VARCHAR USING gender::text"
    )

    # ### end Alembic commands ###
    op.execute("DROP TYPE primary_goal_enum")
    op.execute("DROP TYPE fitness_enum")
    op.execute("DROP TYPE gender_enum")
