"""cascade deletion

Revision ID: e7516f2f090d
Revises: 512d1c99b5d5
Create Date: 2025-08-26 15:06:34.098128

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7516f2f090d"
down_revision: Union[str, Sequence[str], None] = "512d1c99b5d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("workout_plans_user_id_fkey"), "workout_plans", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "workout_plans", "users", ["user_id"], ["user_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_plans", type_="foreignkey")
    op.create_foreign_key(
        op.f("workout_plans_user_id_fkey"),
        "workout_plans",
        "users",
        ["user_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###
