"""user_profile default value set

Revision ID: ebcb6bc0e75e
Revises: dd0c66a2b301
Create Date: 2025-07-24 23:02:27.384108

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebcb6bc0e75e"
down_revision: Union[str, Sequence[str], None] = "dd0c66a2b301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile",
        "fitness_level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="fitness_enum"
        ),
        nullable=False,
    )
    op.alter_column(
        "profile",
        "primary_goal",
        existing_type=postgresql.ENUM(
            "lose_weight",
            "build_muscle",
            "maintain_health",
            "improve_endurance",
            name="primary_goal_enum",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile",
        "primary_goal",
        existing_type=postgresql.ENUM(
            "lose_weight",
            "build_muscle",
            "maintain_health",
            "improve_endurance",
            name="primary_goal_enum",
        ),
        nullable=True,
    )
    op.alter_column(
        "profile",
        "fitness_level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="fitness_enum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
