"""profile default

Revision ID: fad2aab35e37
Revises: 9ab021931889
Create Date: 2025-07-24 23:26:25.986485

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fad2aab35e37"
down_revision: Union[str, Sequence[str], None] = "9ab021931889"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
