"""added multi-column uniqueness constraints

Revision ID: fe3eb93076f3
Revises: 180a2710313a
Create Date: 2025-07-25 21:54:34.264311

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe3eb93076f3"
down_revision: Union[str, Sequence[str], None] = "180a2710313a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_feedback_per_plan_user", "plan_feedback", ["plan_id", "user_id"]
    )
    op.create_unique_constraint(
        "uq_session_exercise", "session_exercises", ["session_id", "exercise_id"]
    )
    op.create_unique_constraint(
        "uq_user_plan_dates", "workout_plans", ["user_id", "valid_from", "valid_to"]
    )
    op.create_unique_constraint(
        "uq_user_session_time", "workout_sessions", ["user_id", "start_time"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_session_time", "workout_sessions", type_="unique")
    op.drop_constraint("uq_user_plan_dates", "workout_plans", type_="unique")
    op.drop_constraint("uq_session_exercise", "session_exercises", type_="unique")
    op.drop_constraint("uq_feedback_per_plan_user", "plan_feedback", type_="unique")
    # ### end Alembic commands ###
