name: Ruff Lint
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry run pip install ruff  # optional: `poetry add --group dev ruff`

      - name: Run Ruff
        run: |
          poetry run ruff check .