name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv pip install -e . --system
          uv pip install pytest pytest-cov --system

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing --tb=short --disable-warnings
